### ISSUE TITLE
Capped version of node

### ISSUE THREAD

**Issue by piotrd** [tuvistavie/lodash-inflection#2]
Hi,

Is there a particular reason why version of node is capped?

```
  "engines": {
    "node": ">=0.10.0 <0.12"
  }
```

I'm using node v0.12.9 and get a warning when installing this package.

**Comment by danhper** [comment]
@piotrd Hi
No reason in particular, I just did not remove it when forking.
It should work perfectly with any version of Node, so I just removed it and published it as 1.3.1.
