### ISSUE TITLE
How do I include this?

### ISSUE THREAD

**Issue by hakunin** [tuvistavie/lodash-inflection#3]
Hi, I am just starting with es6 and react and I know I need to do this to include lodash:

```
import _ from 'lodash';
```

..but how do I include lodash-inflection?

As of now, I get

```
Uncaught TypeError: _lodash2.default.pluralize is not a function
```

**Comment by danhper** [comment]
It is a normal lodash mixin, so you use need to do

``` es6
import _ from 'lodash';
import _inflection from 'lodash-inflection';
_.mixin(_inflection);
```

to get it to work. If you use it often, you can create a module which exports lodash with the module mixed in.

**Comment by hakunin** [comment]
Thanks!

**Comment by gnapse** [comment]
Does this always has to be mixed into lodash? I'm using lodash not by importing it completely, but by individually importing each lodash function I need:

```javascript
import camelCase from 'lodash/camelCase';

console.log(camelCase('hello_world'));
```

Is there a way to include the functions in this library in a similar fashion? Perhaps something like this:

```javascript
import pluralize from 'lodash-inflection/pluralize';
```

**Comment by danhper** [comment]
This is currently not supported, but a PR would be welcome as long as it does not break backward compatibility.
Thanks.

**Comment by pzrq** [comment]
As this issue is closed, apologies for commenting on it.

A colleague suggested I look into `lodash pluralize`, and Google led me here. Another colleague then suggested:

https://www.npmjs.com/package/pluralize

**Comment by danhper** [comment]
Both modules do basically the same thing, the only noticeable difference is probably that this one is a lodash mixin and relies on lodash.
