### ISSUE TITLE
Unable to resolve "./lib-cov..."

### ISSUE THREAD

**Issue by zachdixon** [tuvistavie/lodash-inflection#6]
I started getting this error where it can't find `/lib/lib-cov` which is being required in index.js. The file doesn't exist. I'm not sure what `process.env.JSCOV` and I'm not sure why it's true, which may be the issue?

I'm using this package with Meteor, which is on Node 0.10.43 and npm 2.14.22 currently which may also be the issue? I'm not sure.

For now I just changed the exports to require `lodash-inflection.js` instead and it's working fine.

**Comment by danhper** [comment]
`lib-cov` is generated when running `gulp jscov` and is needed for coverage.
`JSCOV` should not be set to true unless you want to run test coverage.
I think it should work just fine if you unset `JSCOV`.
Could you try and let me know how it goes please?

**Comment by amilajack** [comment]
@tuvistavie I can confirm that using Webpack's DefinePlugin fixed this:
```js
new webpack.DefinePlugin({
  'process.env.JSCOV': JSON.stringify(false),
}),
```
